---
- name: Create and change to actions-runner directory
  hosts: digital-ocean
  remote_user: ysr
  become: yes
  become_user: ysr
  vars:
    directory_path: /home/ysr/projects/actions-runner
    archive_name: actions-runner-linux-x64-2.321.0.tar.gz
    archive_url: https://github.com/actions/runner/releases/download/v2.321.0/{{archive_name}}

  tasks:
    - name: Créer le répertoire
      ansible.builtin.file:
        path: "{{ directory_path }}"
        state: directory
        mode: '0777'
        owner: ysr
      become: yes
      become_user: ysr

    - name: Télécharger l'archive avec curl
      ansible.builtin.get_url:
        url: "{{ archive_url }}"
        dest: "{{ directory_path }}/{{archive_name}}"
        owner: ysr
      become: yes
      become_user: ysr

    - name:  Validate the hash
      shell: echo "ba46ba7ce3a4d7236b16fbe44419fb453bc08f866b24f04d549ec89f1722a29e  {{ directory_path }}/{{archive_name}}" | shasum -a 256 -c

    - name: Extract the installer
      ansible.builtin.unarchive:
        src: "{{ directory_path }}/{{ archive_name }}"
        dest: "{{ directory_path }}"
        remote_src: yes
        owner: ysr
      become: yes
      become_user: ysr

    - name: Configurer le runner
      command: "{{ directory_path }}/config.sh --url https://github.com/dirakkk/vitrine-next --token AB6UYJNE7KVPMCZOLHBPVZLHL3P4C"
      become: yes