---
- hosts: digital-ocean
  become: true
  tasks:
    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Install Next.js globally
      npm:
        name: next
        global: yes
        state: present

    - name: Create Next.js project directory
      file:
        path: /home/ysr/projects/vitrine
        state: directory
